emkopo/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

admin.site.site_header = settings.APP_NAME

urlpatterns = [
    path('admin/', admin.site.urls),
    path("dashboard/", include("emkopo_dashboard.urls")),
    path("loan/", include("emkopo_loan.urls")),
    path("product/", include("emkopo_product.urls")),
    path("api/", include("emkopo_api.urls")),
    path("", include("emkopo_auth.urls"))
]

emkopo_auth/urls.py
from django.urls import path

from emkopo_auth.views import LoginView, LogoutView

app_name = "emkopo_auth"

urlpatterns = [
    path('', LoginView.as_view(redirect_authenticated_user=True), name="login"),
    path('logout/', LogoutView.as_view(template_name="emkopo_auth/bootstrap/login.html"),
         name="logout",),
]

emkopo_dashboard/urls.py
from django.contrib import admin
from django.urls import path

from emkopo_dashboard.views.theme_view import change_theme
from emkopo_dashboard.views.welcome_views import WelcomeView

app_name = "emkopo_dashboard"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("change-theme", change_theme, name="change-theme"),
    path("", WelcomeView.as_view(), name="welcome"),
    ]

emkopo_loan/urls.py
from django.urls import path

from emkopo_loan.views import LoanOfferRequestView, PendingGotApprovalView, \
    LoanDisbursementRequestView
from emkopo_loan.views.loan_disbursement_request import add_disbursement_response
from emkopo_loan.views.loan_offer_request import add_offer_response

app_name = "emkopo_loan"

urlpatterns = [
    path("offer-request/", LoanOfferRequestView.as_view(), name="offer-request"),
    path("pending-got-approval/", PendingGotApprovalView.as_view(), name="pending-got-approval"),
    path("loan-disbursement-request/", LoanDisbursementRequestView.as_view(), name="loan-disbursement-request"),
    path('add-offer-response/', add_offer_response, name="add-offer-response"),
    path("add-disbursement_response/", add_disbursement_response, name="add-disbursement_response"),
]

emkopo_product/urls.py
from django.urls import path

from emkopo_product.views import FspView, ProductCatalogView
from emkopo_product.views.fsp_view import add_fsp, update_fsp, delete_fsp
from emkopo_product.views.product_catalog_view import add_product, add_currency, \
    update_product, delete_product, add_terms, update_terms, delete_terms

app_name = "emkopo_product"

urlpatterns = [
    path("fsp/", FspView.as_view(), name="fsp"),
    path("product-catalog/", ProductCatalogView.as_view(), name="product-catalog"),
    path("add-fsp/", add_fsp, name="add-fsp"),
    path("add-currency/", add_currency, name="add-currency"),
    path("add-product/", add_product, name="add-product"),
    path("add-terms/", add_terms, name="add-terms"),
    path("update-fsp/", update_fsp, name="update-fsp"),
    path("update-terms/", update_terms, name="update-terms"),
    path("update-product/", update_product, name="update-product"),
    path("delete-fsp/", delete_fsp, name="delete-fsp"),
    path("delete-product/", delete_product, name="delete-product"),
    path("delete-terms/", delete_terms, name="delete-terms"),
    ]

emkopo_dashboard/models/app_theme.py
from django.db import models
from simple_history.models import HistoricalRecords

from emkopo_mixins.model import BaseUuidModel
from ..choices import THEME
from ..constants import LIGHT, DARK_THEME


class AppTheme(BaseUuidModel):
    theme_mode = models.CharField(
        verbose_name="Theme",
        max_length=8,
        choices=THEME,
        default=LIGHT,
    )
    theme_name = models.CharField(
        verbose_name="Theme Name",
        max_length=24,
        default=DARK_THEME,
    )
    theme_user = models.CharField(
        verbose_name="Username",
        max_length=12,
        blank=True,
        null=True,
    )

    history = HistoricalRecords()

    def __str__(self):
        return self.theme_user

    class Meta(BaseUuidModel.Meta):
        verbose_name = "App Theme"
        verbose_name_plural = "App Theme"

emkopo_dashboard/views/theme_view.py
from django.shortcuts import redirect
from django.urls import reverse

from emkopo_dashboard.models import AppTheme


def change_theme(request):
    usr = AppTheme.objects.filter(theme_user=request.user)
    if usr:
        AppTheme.objects.filter(theme_user=request.user).update(
            theme_name=request.GET.get("name"),
            theme_mode=request.GET.get("mode"),
        )
    else:
        AppTheme.objects.get_or_create(
            theme_name=request.GET.get("name"),
            theme_mode=request.GET.get("mode"),
            theme_user=request.user,
        )
    app_name = 'emkopo_dashboard'
    return redirect(reverse(f'{app_name}:welcome'))

emkopo_dashboard/views/welcome_views.py
from django.views.generic.base import TemplateView

from emkopo_auth.mixins import LoginMixin


class WelcomeView(LoginMixin, TemplateView):
    template_name = f"emkopo_dashboard/bootstrap/welcome.html"

    def get_context_data(self, **kwargs):
        menu_category = ''
        context = super().get_context_data(**kwargs)
        context.update()
        return context

emkopo_dashboard/templates/emkopo_dashboard/bootstrap/menu/main-menu.html
<nav class="top-nav">
    <ul>
        <li>
            <a href="{% url 'emkopo_dashboard:welcome' %}" class="top-menu">
                <div class="top-menu__icon"> <i data-lucide="shield"></i> </div>
                <div class="top-menu__title"> DASHBOARD </div>
            </a>
        </li>
        <li>
            <a href="{% url 'emkopo_product:fsp' %}" class="top-menu">
                <div class="top-menu__icon"> <i data-lucide="layout"></i> </div>
                <div class="top-menu__title"> FSP </div>
            </a>
        </li>
        <li>
            <a href="{% url 'emkopo_product:product-catalog' %}" class="top-menu">
                <div class="top-menu__icon"> <i data-lucide="layers"></i> </div>
                <div class="top-menu__title"> PRODUCTS CATALOG </div>
            </a>
        </li>
        <li>
            <a href="javascript:;" class="top-menu">
                <div class="top-menu__icon"> <i data-lucide="briefcase"></i> </div>
                <div class="top-menu__title"> LOANS <i data-lucide="chevron-down" class="top-menu__sub-icon"></i> </div>
            </a>
            <ul class="">
                <li>
                    <a href="{% url 'emkopo_loan:offer-request' %}" class="top-menu">
                        <div class="top-menu__icon"> <i data-lucide="file-minus"></i> </div>
                        <div class="top-menu__title">PENDING ({{org_acronym}}) APPROVAL</div>
                    </a>
                </li>
                <li>
                    <a href="{% url 'emkopo_loan:pending-got-approval' %}" class="top-menu">
                        <div class="top-menu__icon"> <i data-lucide="credit-card"></i> </div>
                        <div class="top-menu__title">PENDING GoT APPROVAL</div>
                    </a>
                </li>
                <li>
                    <a href="{% url 'emkopo_loan:loan-disbursement-request' %}" class="top-menu">
                        <div class="top-menu__icon"> <i data-lucide="clipboard"></i> </div>
                        <div class="top-menu__title"> PENDING DISBURSEMENT </div>
                    </a>
                </li>
                <li>
                    <a href="#" class="top-menu">
                        <div class="top-menu__icon"> <i data-lucide="file-text"></i> </div>
                        <div class="top-menu__title"> ALL LOANS </div>
                    </a>
                </li>
            </ul>
        </li>
    </ul>
</nav>

emkopo_dashboard/templates/emkopo_dashboard/bootstrap/menu/mobile-menu.html
{% load static %}
{% block mobile-menu %}
    <!-- BEGIN: Mobile Menu -->
        <div class="mobile-menu md:hidden">
            <div class="mobile-menu-bar">
                <a href="" class="flex mr-auto">
                    <img alt="e-MKOPO" class="w-6" src="{% static 'dist/images/stanbic.png' %}">
                </a>
                <a href="javascript:;" class="mobile-menu-toggler"> <i data-lucide="bar-chart-2" class="w-8 h-8 text-white transform -rotate-90"></i> </a>
            </div>
            <div class="scrollable">
                <a href="javascript:;" class="mobile-menu-toggler"> <i data-lucide="x-circle" class="w-8 h-8 text-white transform -rotate-90"></i> </a>
                <ul class="scrollable__content py-2">
                    <li>
                        <a href="{% url 'emkopo_dashboard:welcome' %}" class="menu menu--active">
                            <div class="menu__icon"> <i data-lucide="home"></i> </div>
                            <div class="menu__title"> Dashboard <i data-lucide="chevron-down" class="menu__sub-icon"></i></div>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'emkopo_product:fsp' %}" class="top-menu">
                            <div class="top-menu__icon"> <i data-lucide="layout"></i> </div>
                            <div class="top-menu__title"> FSP </div>
                        </a>
                    </li>
                    <li>
                        <a href="#" class="menu">
                            <div class="menu__icon"> <i data-lucide="file-plus"></i> </div>
                            <div class="menu__title"> Add Product <i data-lucide="chevron-down" class="menu__sub-icon "></i> </div>
                        </a>
                    </li>
                    <li>
                        <a href="#" class="menu">
                            <div class="menu__icon"> <i data-lucide="file-text"></i> </div>
                            <div class="menu__title"> Product List <i data-lucide="chevron-down" class="menu__sub-icon "></i> </div>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    <!-- END: Mobile Menu -->
{% endblock %}

emkopo_dashboard/templates/emkopo_dashboard/bootstrap/menu/top-bar-menu.html
{% load static %}
{% block top-bar-menu %}
    <!-- BEGIN: Top Bar -->
    <div class="top-bar-boxed top-bar-boxed--top-menu h-[70px] md:h-[65px] z-[51] border-b border-white/[0.08] mt-12 md:mt-0 -mx-3 sm:-mx-8 md:-mx-0 px-3 md:border-b-0 relative md:fixed md:inset-x-0 md:top-0 sm:px-8 md:px-10 md:pt-10 md:bg-gradient-to-b md:from-slate-100 md:to-transparent dark:md:from-darkmode-700">
        <div class="h-full flex items-center">
            <!-- BEGIN: Logo -->
            <a href="{% url 'emkopo_dashboard:welcome' %}" class="logo -intro-x hidden md:flex xl:w-[180px] block">
                <img alt="SBT LOGO" class="logo__image w-6" src="{% static 'dist/images/stanbic.png' %}">
                <span class="logo__text text-white text-lg ml-3"> e-MKOPO </span>
            </a>
            <!-- END: Logo -->
            <!-- BEGIN: Breadcrumb -->
            <nav aria-label="breadcrumb" class="-intro-x h-[45px] mr-auto">
                <ol class="breadcrumb breadcrumb-light">
                    <li class="breadcrumb-item"><a href="#">Application</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Dashboard</li>
                </ol>
            </nav>
            <!-- END: Breadcrumb -->
            <!-- BEGIN: Search -->
{#            {% if no_approve > 0 %}#}
{#                <div class="intro-x relative mr-3 sm:mr-6">#}
{#                    <a href="{% url 'somans_dashboard:approve-sft-req' %}" class="btn btn-outline-danger w-1/2 sm:w-auto mr-2" style="color: #f8f8f8"> <i class="w-4 h-4 mr-2" style="color: #f8f8f8"> {{ no_approve }} </i> Approval Request </a>#}
{#                </div>#}
{#            {% endif %}#}
{#            {% if no_dca_request > 0 %}#}
{#                <div class="intro-x relative mr-3 sm:mr-6">#}
{#                    <a href="{% url 'SBT-dap:dap-approval' %}" class="btn btn-outline-danger #}
{#                    w-1/2 sm:w-auto mr-2" style="color: #f8f8f8"> <i class="w-4 h-4 mr-2" style="color: #f8f8f8"> {{ no_dca_request }} </i> DCA Request </a>#}
{#                </div>#}
{#            {% endif %}#}
            <!-- END: Search -->
            <!-- BEGIN: Notifications -->
{#               <div class="intro-x dropdown mr-4 sm:mr-6">#}
{#                   <div class="dropdown-toggle notification notification--bullet cursor-pointer" role="button" aria-expanded="false" data-tw-toggle="dropdown"> <i data-lucide="bell" class="notification__icon dark:text-slate-500"></i> </div>#}
{#                   <div class="notification-content pt-2 dropdown-menu">#}
{#                       <div class="notification-content__box dropdown-content">#}
{#                           <div class="notification-content__title">Notifications</div>#}
{#                            <div class="cursor-pointer relative flex items-center ">#}
{#                                <div class="w-12 h-12 flex-none image-fit mr-1">#}
{#                                    <img alt="SOMANS Icon" class="rounded-full" src="{% static 'dist/images/profile-6.jpg' %}">#}
{#                                    <div class="w-3 h-3 bg-success absolute right-0 bottom-0 rounded-full border-2 border-white"></div>#}
{#                                </div>#}
{#                                <div class="ml-2 overflow-hidden">#}
{#                                    <div class="flex items-center">#}
{#                                        <a href="javascript:;" class="font-medium truncate mr-5">New installed software</a>#}
{#                                        <div class="text-xs text-slate-400 ml-auto whitespace-nowrap">01:10 PM</div>#}
{#                                    </div>#}
{#                                    <div class="w-full truncate text-slate-500 mt-0.5">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry&#039;s standard dummy text ever since the 1500</div>#}
{#                                </div>#}
{#                            </div>#}
{#                        </div>#}
{#                    </div>#}
{#                </div>#}
                <!-- END: Notifications -->
                <!-- BEGIN: Account Menu -->
            <div class="intro-x dropdown w-8 h-8">
                <div class="dropdown-toggle w-8 h-8 rounded-full overflow-hidden shadow-lg image-fit zoom-in scale-110" role="button" aria-expanded="false" data-tw-toggle="dropdown">
                    <img alt="SBT" src="{% static 'dist/images/blank.png' %}">
                </div>
                <div class="dropdown-menu w-56">
                    <ul class="dropdown-content bg-primary/80 before:block before:absolute before:bg-black before:inset-0 before:rounded-md before:z-[-1] text-white">
                        <li class="p-2">
                            <div class="font-medium">{{ username }}</div>
                            <div class="text-xs text-white/60 mt-0.5 dark:text-slate-500">Emkopo Admin</div>
                        </li>
                        <li>
                            <hr class="dropdown-divider border-white/[0.08]">
                        </li>
                        <li>
                            <a href="" class="dropdown-item hover:bg-white/5"> <i data-lucide="user" class="w-4 h-4 mr-2"></i> Profile </a>
                        </li>
                        <li>
                            <a href="{% url 'admin:index' %}" class="dropdown-item hover:bg-white/5"> <i data-lucide="edit" class="w-4 h-4 mr-2"></i> Administration </a>
                        </li>
                        <li>
                            <a href="" class="dropdown-item hover:bg-white/5"> <i data-lucide="lock" class="w-4 h-4 mr-2"></i> Reset Password </a>
                        </li>
                        <li>
                            <a href="" class="dropdown-item hover:bg-white/5"> <i data-lucide="help-circle" class="w-4 h-4 mr-2"></i> Help </a>
                        </li>
                        <li>
                            <hr class="dropdown-divider border-white/[0.08]">
                        </li>
                        <li>
                            <a href="{% url 'emkopo_auth:logout' %}" class="dropdown-item hover:bg-white/5"> <i data-lucide="toggle-right" class="w-4 h-4 mr-2"></i> Logout </a>
                        </li>
                    </ul>
                </div>
            </div>
            <!-- END: Account Menu -->
        </div>
    </div>
    <!-- END: Top Bar -->
{% endblock %}