emkopo/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

admin.site.site_header = settings.APP_NAME

urlpatterns = [
    path('admin/', admin.site.urls),
    path("dashboard/", include("emkopo_dashboard.urls")),
    path("loan/", include("emkopo_loan.urls")),
    path("product/", include("emkopo_product.urls")),
    path("api/", include("emkopo_api.urls")),
    path("", include("emkopo_auth.urls"))
]

emkopo_dashboard/urls.py
from django.contrib import admin
from django.urls import path

from emkopo_dashboard.views.theme_view import change_theme
from emkopo_dashboard.views.welcome_views import WelcomeView

app_name = "emkopo_dashboard"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("change-theme", change_theme, name="change-theme"),
    path("", WelcomeView.as_view(), name="welcome"),
    ]

emkopo_dashboard/models/app_theme.py
from django.db import models
from simple_history.models import HistoricalRecords

from emkopo_mixins.model import BaseUuidModel
from ..choices import THEME
from ..constants import LIGHT, DARK_THEME


class AppTheme(BaseUuidModel):
    theme_mode = models.CharField(
        verbose_name="Theme",
        max_length=8,
        choices=THEME,
        default=LIGHT,
    )
    theme_name = models.CharField(
        verbose_name="Theme Name",
        max_length=24,
        default=DARK_THEME,
    )
    theme_user = models.CharField(
        verbose_name="Username",
        max_length=12,
        blank=True,
        null=True,
    )

    history = HistoricalRecords()

    def __str__(self):
        return self.theme_user

    class Meta(BaseUuidModel.Meta):
        verbose_name = "App Theme"
        verbose_name_plural = "App Theme"

emkopo_dashboard/views/theme_view.py
from django.shortcuts import redirect
from django.urls import reverse

from emkopo_dashboard.models import AppTheme


def change_theme(request):
    usr = AppTheme.objects.filter(theme_user=request.user)
    if usr:
        AppTheme.objects.filter(theme_user=request.user).update(
            theme_name=request.GET.get("name"),
            theme_mode=request.GET.get("mode"),
        )
    else:
        AppTheme.objects.get_or_create(
            theme_name=request.GET.get("name"),
            theme_mode=request.GET.get("mode"),
            theme_user=request.user,
        )
    app_name = 'emkopo_dashboard'
    return redirect(reverse(f'{app_name}:welcome'))

emkopo_dashboard/views/welcome_views.py
from django.views.generic.base import TemplateView

from emkopo_auth.mixins import LoginMixin


class WelcomeView(LoginMixin, TemplateView):
    template_name = f"emkopo_dashboard/bootstrap/welcome.html"

    def get_context_data(self, **kwargs):
        menu_category = ''
        context = super().get_context_data(**kwargs)
        context.update()
        return context

emkopo_dashboard/templates/emkopo_dashboard/bootstrap/buttons/pagination.html
<div class="intro-y col-span-12 flex flex-wrap sm:flex-row sm:flex-nowrap items-center">
    <nav class="w-full sm:w-auto sm:mr-auto">
        <ul class="pagination">
{#            <li class="page-item">#}
{#                <a class="page-link" href="#"> <i class="w-4 h-4" data-lucide="chevrons-left"></i> </a>#}
{#            </li>#}
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="{{ page_obj.previous_page_number }}"> <i class="w-4 h-4" data-lucide="chevron-left"></i> </a>
                </li>
            {% endif %}
            {% for num in num_pages %}
                <li class="page-item {% if forloop.counter == page_obj.number %}active{% endif %}">
                    <a href="{{ forloop.counter }}" class="page-link">{{ forloop.counter }}</a>
                </li>
            {% endfor %}
            
            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="{{ page_obj.next_page_number }}"> <i class="w-4 h-4" data-lucide="chevron-right"></i> </a>
                </li>
            {% endif %}
{#            <li class="page-item">#}
{#                <a class="page-link" href="{{ Page.end_index }}"> <i class="w-4 h-4" data-lucide="chevrons-right"></i> </a>#}
{#            </li>#}
        </ul>
    </nav>
</div><br>

emkopo_dashboard/templates/emkopo_dashboard/bootstrap/buttons/theme_button.html
<div data-url="{% url 'emkopo_dashboard:change-theme' %}{{ theme_url }}" class="dark-mode-switcher cursor-pointer shadow-md fixed bottom-0 right-0 box dark:bg-dark-2 border rounded-full w-40 h-12 flex items-center justify-center z-50 mb-10 mr-10">
    <div class="form-check form-switch">
        <input id="checkbox-switch-7" class="form-check-input" type="checkbox" value="">
        <label class="form-check-label" for="checkbox-switch-7">{{ theme_name }}</label>
    </div>
</div>