emkopo/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

admin.site.site_header = settings.APP_NAME

urlpatterns = [
    path('admin/', admin.site.urls),
    path("dashboard/", include("emkopo_dashboard.urls")),
    path("loan/", include("emkopo_loan.urls")),
    path("product/", include("emkopo_product.urls")),
    path("api/", include("emkopo_api.urls")),
    path("", include("emkopo_auth.urls"))
]

emkopo_loan/urls.py
from django.urls import path

from emkopo_loan.views import LoanOfferRequestView, PendingGotApprovalView, \
    LoanDisbursementRequestView
from emkopo_loan.views.loan_disbursement_request import add_disbursement_response
from emkopo_loan.views.loan_offer_request import add_offer_response

app_name = "emkopo_loan"

urlpatterns = [
    path("offer-request/", LoanOfferRequestView.as_view(), name="offer-request"),
    path("pending-got-approval/", PendingGotApprovalView.as_view(), name="pending-got-approval"),
    path("loan-disbursement-request/", LoanDisbursementRequestView.as_view(), name="loan-disbursement-request"),
    path('add-offer-response/', add_offer_response, name="add-offer-response"),
    path("add-disbursement_response/", add_disbursement_response, name="add-disbursement_response"),
]

emkopo_loan/models.py
from django.db import models

# Create your models here.

emkopo_loan/models/account_validation_request.py
from django.db import models
from django.utils import timezone
from simple_history.models import HistoricalRecords

from emkopo_constants.choices import REQUEST_TYPE
from emkopo_mixins.model import BaseUuidModel


class AccountValidationRequest(BaseUuidModel):
    AccountNumber = models.CharField(
        verbose_name="Account Number",
        max_length=455,
    )
    FirstName = models.CharField(
        verbose_name="First Name",
        max_length=45,
    )
    MiddleName = models.CharField(
        verbose_name="Middle Name",
        max_length=45,
    )
    LastName = models.CharField(
        verbose_name="Last Name",
        max_length=45,
    )
    MessageType = models.CharField(
        verbose_name="Message Type",
        max_length=100,
    )
    RequestType = models.CharField(
        verbose_name="Request Type",
        max_length=45,
        choices=REQUEST_TYPE,
    )
    Timestamp = models.DateTimeField(
        verbose_name="Timestamp",
        default=timezone.now
    )
    status = models.IntegerField(
        verbose_name="Status",
        default=1,
    )

    history = HistoricalRecords()

    def __str__(self):
        return f'{self.AccountNumber}'

    class Meta(BaseUuidModel.Meta):
        verbose_name = "Account Validation Request"
        verbose_name_plural = "Account Validation Requests"

emkopo_loan/models/account_validation_response.py
from django.db import models
from django.utils import timezone
from simple_history.models import HistoricalRecords

from emkopo_constants.choices import REQUEST_TYPE
from emkopo_mixins.model import BaseUuidModel


class AccountValidationResponse(BaseUuidModel):
    AccountNumber = models.CharField(
        verbose_name="Account Number",
        max_length=45,
    )
    Valid = models.BooleanField(
        verbose_name="Valid",
    )
    Reason = models.CharField(
        verbose_name="Reason",
        max_length=120,
    )
    MessageType = models.CharField(
        verbose_name="Message Type",
        max_length=100,
    )
    RequestType = models.CharField(
        verbose_name="Request Type",
        max_length=45,
        choices=REQUEST_TYPE,
    )
    Timestamp = models.DateTimeField(
        verbose_name="Timestamp",
        default=timezone.now
    )
    status = models.IntegerField(
        verbose_name="Status",
        default=1,
    )

    history = HistoricalRecords()

    def __str__(self):
        return f'{self.MessageType}'

    class Meta(BaseUuidModel.Meta):
        verbose_name = "Account Validation Response"
        verbose_name_plural = "Account Validation Responses"

emkopo_loan/models/deduction_stop_notification.py
from django.db import models
from django.utils import timezone
from simple_history.models import HistoricalRecords

from emkopo_constants.choices import REQUEST_TYPE
from emkopo_mixins.model import BaseUuidModel


class LoanDeductionStopNotification(BaseUuidModel):
    FSPReferenceNumber = models.CharField(
        verbose_name="FSP Reference Number",
        max_length=45,
    )
    LoanNumber = models.CharField(
        verbose_name="Loan Number",
        max_length=20,
    )
    CheckNumber = models.IntegerField(
        verbose_name="Check number",
    )
    FirstName = models.CharField(
        verbose_name="First Name",
        max_length=30,
    )
    MiddleName = models.CharField(
        verbose_name="Middle Name",
        max_length=30,
    )
    LastName = models.CharField(
        verbose_name="Last Name",
        max_length=30,
    )
    NationalId = models.CharField(
        verbose_name="National ID",
        max_length=45,
    )
    VoteCode = models.CharField(
        verbose_name="Vote code",
        max_length=6,
    )
    VoteName = models.CharField(
        verbose_name="Vote name",
        max_length=255,
    )
    DepartmentCode = models.CharField(
        verbose_name="Department Code",
        max_length=45,
    )
    DepartmentName = models.CharField(
        verbose_name="Department Name",
        max_length=45,
    )
    DeductionCode = models.CharField(
        verbose_name="Deduction Code",
        max_length=45,
    )
    DeductionDescription = models.CharField(
        verbose_name="Deduction Description",
        max_length=120,
    )
    BalanceAmount = models.DecimalField(
        verbose_name="Balance Amount",
        max_digits=40,
        decimal_places=2,
    )
    DeductionAmount = models.DecimalField(
        verbose_name="Deduction Amount",
        max_digits=40,
        decimal_places=2,
    )
    StopDate = models.DateField(
        verbose_name="Stop Date",
    )
    StopReason = models.CharField(
        verbose_name="Stop Reason",
        max_length=255,
        blank=True,
        null=True,
    )
    StopPayReason = models.CharField(
        verbose_name="Stop pay reason",
        max_length=255,
        blank=True,
        null=True,
    )
    Timestamp = models.DateTimeField(
        verbose_name="Timestamp",
        default=timezone.now
    )
    status = models.IntegerField(
        verbose_name="Status",
        default=1,
    )
    MessageType = models.CharField(
        verbose_name="Message Type",
        max_length=100,
    )
    RequestType = models.CharField(
        verbose_name="Request Type",
        max_length=45,
        choices=REQUEST_TYPE,
    )

    history = HistoricalRecords()

    def __str__(self):
        return f'{self.CheckNumber} : {self.LoanNumber}'

    class Meta(BaseUuidModel.Meta):
        verbose_name = "Loan Deduction Stop Notification"
        verbose_name_plural = "Loan Deduction Stop Notifications"

emkopo_loan/models/defaulter_detail_employer.py
from django.db import models
from django.utils import timezone
from simple_history.models import HistoricalRecords

from emkopo_constants.choices import REQUEST_TYPE
from emkopo_mixins.model import BaseUuidModel


class LoanDefaulterDetailEmployer(BaseUuidModel):
    CheckNumber = models.CharField(
        verbose_name="CheckNumber",
        max_length=45,
    )
    LoanNumber = models.CharField(
        verbose_name="Loan Number",
        max_length=45,
    )
    VoteName = models.CharField(
        verbose_name="Vote Name",
        max_length=255,
    )
    FirstName = models.CharField(
        verbose_name="First Name",
        max_length=45,
    )
    MiddleName = models.CharField(
        verbose_name="Middle Name",
        max_length=45,
    )
    LastName = models.CharField(
        verbose_name="Last Name",
        max_length=45,
    )
    InstallationAmount = models.DecimalField(
        verbose_name="Installation Amount",
        decimal_places=2,
        max_digits=40,
    )
    DeductionAmount = models.DecimalField(
        verbose_name="Deduction Amount",
        decimal_places=2,
        max_digits=40,
    )
    DeductionCode = models.CharField(
        verbose_name="Deduction Code",
        max_length=45,
    )
    DeductionName = models.CharField(
        verbose_name="Deduction Name",
        max_length=45,
    )
    OutstandingBalance = models.DecimalField(
        verbose_name="Outstanding Balance",
        decimal_places=2,
        max_digits=40,
    )
    LastPayDate = models.DateField(
        verbose_name="Last Payment Date",
    )
    MessageType = models.CharField(
        verbose_name="Message Type",
        max_length=100,
    )
    RequestType = models.CharField(
        verbose_name="Request Type",
        max_length=45,
        choices=REQUEST_TYPE,
    )
    Timestamp = models.DateTimeField(
        verbose_name="Timestamp",
        default=timezone.now
    )
    status = models.IntegerField(
        verbose_name="Status",
        default=1,
    )

    history = HistoricalRecords()

    def __str__(self):
        return f'{self.CheckNumber}'

    class Meta(BaseUuidModel.Meta):
        verbose_name = "Loan Defaulter Detail Employer"
        verbose_name_plural = "Loan Defaulter Detail Employer"

emkopo_loan/models/full_loan_repayment_notification.py
from django.db import models
from django.utils import timezone
from simple_history.models import HistoricalRecords

from emkopo_constants.choices import REQUEST_TYPE
from emkopo_mixins.model import BaseUuidModel


class FullLoanRepaymentNotification(BaseUuidModel):
    CheckNumber = models.CharField(
        verbose_name="CheckNumber",
        max_length=45,
    )
    ApplicationNumber = models.CharField(
        verbose_name="Application Number",
        max_length=45,
    )
    LoanNumber = models.CharField(
        verbose_name="Loan Number",
        max_length=45,
    )
    PaymentReference = models.CharField(
        verbose_name="Payment Reference",
        max_length=45,
    )
    DeductionCode = models.CharField(
        verbose_name="Deduction Code",
        max_length=45,
    )
    PaymentDescription = models.CharField(
        verbose_name="Payment Description",
        max_length=125,
    )
    PaymentDate = models.DateTimeField(
        verbose_name="Payment Date",
    )
    PaymentAmount = models.DecimalField(
        verbose_name="Payment Amount",
        decimal_places=2,
        max_digits=40,
    )
    LoanBalance = models.DecimalField(
        verbose_name="Loan Balance",
        decimal_places=2,
        max_digits=40,
    )
    MessageType = models.CharField(
        verbose_name="Message Type",
        max_length=100,
    )
    RequestType = models.CharField(
        verbose_name="Request Type",
        max_length=45,
        choices=REQUEST_TYPE,
    )
    Timestamp = models.DateTimeField(
        verbose_name="Timestamp",
        default=timezone.now
    )
    status = models.IntegerField(
        verbose_name="Status",
        default=1,
    )

    history = HistoricalRecords()

    def __str__(self):
        return f'{self.CheckNumber}'

    class Meta(BaseUuidModel.Meta):
        verbose_name = "Ful Loan Repayment Notification"
        verbose_name_plural = "Full Loan Repayment Notifications"

emkopo_loan/models/full_loan_repayment_request.py
from django.db import models
from django.utils import timezone
from simple_history.models import HistoricalRecords

from emkopo_constants.choices import REQUEST_TYPE
from emkopo_mixins.model import BaseUuidModel


class FullLoanRepaymentRequest(BaseUuidModel):
    CheckNumber = models.CharField(
        verbose_name="CheckNumber",
        max_length=45,
    )
    LoanNumber = models.CharField(
        verbose_name="Loan Number",
        max_length=45,
    )
    FirstName = models.CharField(
        verbose_name="First Name",
        max_length=45,
    )
    MiddleName = models.CharField(
        verbose_name="Middle Name",
        max_length=45,
    )
    LastName = models.CharField(
        verbose_name="Last Name",
        max_length=45,
    )
    VoteCode = models.CharField(
        verbose_name="Vote Code",
        max_length=45,
    )
    VoteName = models.CharField(
        verbose_name="Vote Name",
        max_length=255,
    )
    DeductionAmount = models.DecimalField(
        verbose_name="Deduction Amount",
        decimal_places=2,
        max_digits=40,
    )
    DeductionCode = models.CharField(
        verbose_name="Deduction Code",
        max_length=45,
    )
    DeductionName = models.CharField(
        verbose_name="Deduction Name",
        max_length=45,
    )
    DeductionBalance = models.DecimalField(
        verbose_name="Deduction Balance",
        decimal_places=2,
        max_digits=40,
    )
    PaymentOption = models.CharField(
        verbose_name="Payment Option",
        max_length=45,
    )
    MessageType = models.CharField(
        verbose_name="Message Type",
        max_length=100,
    )
    RequestType = models.CharField(
        verbose_name="Request Type",
        max_length=45,
        choices=REQUEST_TYPE,
    )
    Timestamp = models.DateTimeField(
        verbose_name="Timestamp",
        default=timezone.now
    )
    status = models.IntegerField(
        verbose_name="Status",
        default=1,
    )

    history = HistoricalRecords()

    def __str__(self):
        return f'{self.CheckNumber}'

    class Meta(BaseUuidModel.Meta):
        verbose_name = "Ful Loan Repayment Request"
        verbose_name_plural = "Full Loan Repayment Requests"

emkopo_loan/models/loan_charge_request.py
from django.db import models
from django.utils import timezone
from simple_history.models import HistoricalRecords

from emkopo_constants.choices import REQUEST_TYPE
from emkopo_mixins.model import BaseUuidModel


class LoanChargeRequest(BaseUuidModel):
    CheckNumber = models.IntegerField(
        verbose_name="Check number",
    )
    DesignationCode = models.CharField(
        verbose_name="Designation code",
        max_length=8,
    )
    DesignationName = models.CharField(
        verbose_name="Designation name",
        max_length=255,
    )
    BasicSalary = models.DecimalField(
        verbose_name="Basic Salary",
        max_digits=40,
        decimal_places=2,
    )
    NetSalary = models.DecimalField(
        verbose_name="Net salary",
        max_digits=40,
        decimal_places=2,
    )
    OneThirdAmount = models.DecimalField(
        verbose_name="One third amount",
        max_digits=40,
        decimal_places=2,
    )
    RequestedAmount = models.DecimalField(
        verbose_name="Requested amount",
        max_digits=40,
        decimal_places=2,
        blank=True,
        null=True,
    )
    DeductibleAmount = models.DecimalField(
        verbose_name="Deductible amount",
        max_digits=40,
        decimal_places=2,
    )
    DesiredDeductibleAmount = models.DecimalField(
        verbose_name="Desired deductible amount",
        max_digits=40,
        decimal_places=2,
        blank=True,
        null=True,
    )
    RetirementDate = models.IntegerField(
        verbose_name="Retirement date",
    )
    TermsOfEmployment = models.CharField(
        verbose_name="Terms of employment",
        max_length=30,
    )
    Tenure = models.IntegerField(
        verbose_name="Tenure",
        blank=True,
        null=True,
    )
    ProductCode = models.CharField(
        verbose_name="Product code",
        max_length=8,
    )
    VoteCode = models.CharField(
        verbose_name="Vote Code",
        max_length=10,
    )
    TotalEmployeeDeduction = models.DecimalField(
        verbose_name="Total Employee Deduction",
        max_digits=40,
        decimal_places=2,
        blank=True,
        null=True,
    )
    JobClassCode = models.CharField(
        verbose_name="Job class code",
        max_length=10,
    )
    MessageType = models.CharField(
        verbose_name="Message Type",
        max_length=100,
    )
    RequestType = models.CharField(
        verbose_name="Request Type",
        max_length=45,
        choices=REQUEST_TYPE,
    )
    Timestamp = models.DateTimeField(
        verbose_name="Timestamp",
        default=timezone.now
    )
    status = models.IntegerField(
        verbose_name="Status",
        default=1,
    )

    history = HistoricalRecords()

    def __str__(self):
        return f'{self.CheckNumber} : {self.DesignationName}'

    class Meta(BaseUuidModel.Meta):
        verbose_name = "Loan Charge Request"
        verbose_name_plural = "Loan Charge Requests"

emkopo_loan/templates/emkopo_loan/bootstrap/button/loan-disbursement.html
<a href="javascript:;" data-tw-toggle="modal" data-tw-target="#loan-disburse-{{ num }}" class="btn btn-success mr-1 mb-1">Disbursement</a>
<div id="loan-disburse-{{ num }}" class="modal" tabindex="-1" data-tw-backdrop="static" aria-hidden="true">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="intro-y box mt-5">
                <div class="flex flex-col sm:flex-row items-center p-5 border-b border-slate-200/60 dark:border-darkmode-400">
                    <h2 class="font-medium text-base mr-auto">
                        LOAN OFFER DISBURSEMENT
                    </h2>
                </div>
                <div id="input-groups" class="p-5">
                    <div class="preview">
                        <form action="{% url 'emkopo_loan:add-disbursement_response' %}" method="post">
                            {% csrf_token %}
                            <div>
                                <label>Have you reviewed this request to ensure that it complies with the business rules for acceptance or rejection?</label>
                                <div class="form-check mt-2">
                                    <input id="radio-switch-1" class="form-check-input" type="radio" name="FspComplies" value="yes" required>
                                    <label class="form-check-label" for="radio-switch-1">Yes</label>
                                </div>
                                <div class="form-check mt-2">
                                    <input id="radio-switch-2" class="form-check-input" type="radio" name="FspComplies" value="no" required>
                                    <label class="form-check-label" for="radio-switch-2">No</label>
                                </div>
                            </div><br>
                            <div>
                                <label>Did you successful disburse Loan to client account?</label>
                                <div class="form-check mt-2">
                                    <input id="radio-switch-1" class="form-check-input" type="radio" name="FspResponse" value="4" required>
                                    <label class="form-check-label" for="radio-switch-1">Yes</label>
                                </div>
                                <div class="form-check mt-2">
                                    <input id="radio-switch-2" class="form-check-input" type="radio" name="FspResponse" value="5" required>
                                    <label class="form-check-label" for="radio-switch-2">No</label>
                                </div>
                            </div><br>
                            <div class="col-span-12 sm:col-span-12">
                                <label for="fsp-name" class="form-label">Total Amount ToPay</label>
                                <input id="fsp-name" name="TotalAmountToPay" type="number" class="form-control">
                            </div><br>
                            <div class="col-span-12 sm:col-span-6">
                                <label for="fsp-name" class="form-label">Disbursement Date</label>
                                 <input id="fsp-name" name="DisbursementDate" type="text" class="datepicker form-control" data-single-mode="true">
                            </div><br>
                            <div>
                                <label for="regular-form-1" class="form-label">Reasons for this response</label>
                                <textarea id="regular-form-1" name="Reason" type="text" class="form-control" placeholder="Provide reasons for this response" required></textarea>
                            </div><br>
                            <div>
                                <input type="hidden" name="LoanOfferRequest" value="{{ offer_response.LoanOfferRequest.id }}">
                                <input type="hidden" name="id" value="{{ offer_response.id }}">
                                <input type="hidden" name="LoanNumber" value="{{ offer_response.LoanNumber }}">
                                <input type="hidden" name="FSPReferenceNumber" value="{{ offer_response.FSPReferenceNumber }}">
                                <input type="hidden" name="Staff" value="{{ Staff }}">
                                <input type="hidden" name="next_url_name" value="loan-disbursement-request">
                                <input type="submit" value="Submit" class="btn btn-primary w-1/2 sm:w-auto mr-2 pull-right">
                                <button type="button" data-tw-dismiss="modal" class="btn btn-outline-secondary w-20 mr-1">Cancel</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

emkopo_loan/templates/emkopo_loan/bootstrap/button/offer-response.html
<a href="javascript:;" data-tw-toggle="modal" data-tw-target="#offer-response-{{ num }}" class="btn btn-success mr-1 mb-1">Response</a>
<div id="offer-response-{{ num }}" class="modal" tabindex="-1" data-tw-backdrop="static" aria-hidden="true">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="intro-y box mt-5">
                <div class="flex flex-col sm:flex-row items-center p-5 border-b border-slate-200/60 dark:border-darkmode-400">
                    <h2 class="font-medium text-base mr-auto">
                        LOAN OFFER RESPONSE
                    </h2>
                </div>
                <div id="input-groups" class="p-5">
                    <div class="preview">
                        <form action="{% url 'emkopo_loan:add-offer-response' %}" method="post">
                            {% csrf_token %}
                            <div>
                                <label>Have you reviewed this request to ensure that it complies with the business rules for acceptance or rejection?</label>
                                <div class="form-check mt-2">
                                    <input id="radio-switch-1" class="form-check-input" type="radio" name="FspComplies" value="yes" required>
                                    <label class="form-check-label" for="radio-switch-1">Yes</label>
                                </div>
                                <div class="form-check mt-2">
                                    <input id="radio-switch-2" class="form-check-input" type="radio" name="FspComplies" value="no" required>
                                    <label class="form-check-label" for="radio-switch-2">No</label>
                                </div>
                            </div><br>
                            <div>
                                <label>Offer Response?</label>
                                <div class="form-check mt-2">
                                    <input id="radio-switch-1" class="form-check-input" type="radio" name="FspResponse" value="2" required>
                                    <label class="form-check-label" for="radio-switch-1">ACCEPT</label>
                                </div>
                                <div class="form-check mt-2">
                                    <input id="radio-switch-2" class="form-check-input" type="radio" name="FspResponse" value="9" required>
                                    <label class="form-check-label"for="radio-switch-2">REJECT</label>
                                </div>
                            </div><br>
                            <div class="col-span-12 sm:col-span-12">
                                <label for="fsp-name" class="form-label">Total Amount ToPay</label>
                                <input id="fsp-name" name="TotalAmountToPay" type="number" class="form-control">
                            </div><br>
                            <div class="col-span-6 sm:col-span-6">
                                <label for="fsp-name" class="form-label">Other Charges</label>
                                <input id="fsp-name" name="OtherCharges" type="number" class="form-control">
                            </div><br>
                            <div>
                                <label for="regular-form-1" class="form-label">Reasons for this response</label>
                                <textarea id="regular-form-1" name="Reason" type="text" class="form-control" placeholder="Provide reasons for this response" required></textarea>
                            </div><br>
                            <div>
                                <input type="hidden" name="LoanOfferRequest" value="{{ loan.id }}">
                                <input type="hidden" name="LoanOfferType" value="{{ loan.LoanOfferType }}">
                                <input type="hidden" name="Staff" value="{{ Staff }}">
                                <input type="hidden" name="next_url_name" value="offer-request">
                                <input type="submit" value="Submit" class="btn btn-primary w-1/2 sm:w-auto mr-2 pull-right">
                                <button type="button" data-tw-dismiss="modal" class="btn btn-outline-secondary w-20 mr-1">Cancel</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>