emkopo/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

admin.site.site_header = settings.APP_NAME

urlpatterns = [
    path('admin/', admin.site.urls),
    path("dashboard/", include("emkopo_dashboard.urls")),
    path("loan/", include("emkopo_loan.urls")),
    path("product/", include("emkopo_product.urls")),
    path("api/", include("emkopo_api.urls")),
    path("", include("emkopo_auth.urls"))
]

emkopo_product/urls.py
from django.urls import path

from emkopo_product.views import FspView, ProductCatalogView
from emkopo_product.views.fsp_view import add_fsp, update_fsp, delete_fsp
from emkopo_product.views.product_catalog_view import add_product, add_currency, \
    update_product, delete_product, add_terms, update_terms, delete_terms

app_name = "emkopo_product"

urlpatterns = [
    path("fsp/", FspView.as_view(), name="fsp"),
    path("product-catalog/", ProductCatalogView.as_view(), name="product-catalog"),
    path("add-fsp/", add_fsp, name="add-fsp"),
    path("add-currency/", add_currency, name="add-currency"),
    path("add-product/", add_product, name="add-product"),
    path("add-terms/", add_terms, name="add-terms"),
    path("update-fsp/", update_fsp, name="update-fsp"),
    path("update-terms/", update_terms, name="update-terms"),
    path("update-product/", update_product, name="update-product"),
    path("delete-fsp/", delete_fsp, name="delete-fsp"),
    path("delete-product/", delete_product, name="delete-product"),
    path("delete-terms/", delete_terms, name="delete-terms"),
    ]

emkopo_product/models/branch.py
from django.db import models
from simple_history.models import HistoricalRecords

from emkopo_mixins.model import BaseUuidModel
from .district import District


class Branch(BaseUuidModel):
    District = models.ForeignKey(
        District,
        on_delete=models.CASCADE,
        related_query_name='district',
        verbose_name="District",
    )
    BranchCode = models.CharField(
        verbose_name="Branch Code",
        max_length=120,
    )
    BranchName = models.CharField(
        verbose_name="Branch Name",
        max_length=255,
    )
    active = models.BooleanField(
        verbose_name="Status",
        default=True,
    )

    history = HistoricalRecords()

    def __str__(self):
        return self.BranchCode

    class Meta(BaseUuidModel.Meta):
        verbose_name = "Branch"
        verbose_name_plural = "Branches"

emkopo_product/models/currency.py
from django.db import models
from simple_history.models import HistoricalRecords

from emkopo_mixins.model import BaseUuidModel


class Currency(BaseUuidModel):
    name = models.CharField(
        verbose_name="Currency Name",
        max_length=45,
    )
    code = models.CharField(
        verbose_name="Currency Code",
        max_length=10,
    )
    status = models.IntegerField(
        verbose_name="Currency Status",
        default=1,
    )

    history = HistoricalRecords()

    def __str__(self):
        return self.name

    class Meta(BaseUuidModel.Meta):
        verbose_name = "Currency"
        verbose_name_plural = "Currency"

emkopo_product/models/district.py
from django.db import models
from simple_history.models import HistoricalRecords

from emkopo_mixins.model import BaseUuidModel


class District(BaseUuidModel):
    DistrictNane = models.CharField(
        verbose_name="District Name",
        max_length=120,
    )
    DistrictCode = models.CharField(
        verbose_name="District Code",
        max_length=45,
    )
    active = models.BooleanField(
        verbose_name="Status",
        default=True
    )

    history = HistoricalRecords()

    def __str__(self):
        return self.DistrictCode

    class Meta(BaseUuidModel.Meta):
        verbose_name = "District"
        verbose_name_plural = "Districts"

emkopo_product/views/fsp_view.py
from django.views.generic.base import TemplateView
from django.shortcuts import redirect
from django.urls import reverse

from emkopo_auth.mixins import LoginMixin
from emkopo_product.models import Fsp


class FspView(LoginMixin, TemplateView):
    template_name = f"emkopo_product/bootstrap/fsp.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        fsps = Fsp.objects.filter(status=1)
        context.update(
            fsps=fsps
        )
        return context


def add_fsp(request):
    if request.method == 'POST':
        created = Fsp.objects.get_or_create(
            name=request.POST['name'],
            code=request.POST['code'],
            sysName=request.POST.get("sysName"),
            FSPBankAccount=request.POST.get("FSPBankAccount"),
            FSPBankAccountName=request.POST.get("FSPBankAccountName"),
            SWIFTCode=request.POST.get("SWIFTCode"),
            MNOChannels=request.POST.get("MNOChannels"),
        )

        if created:
            res = 'success'
            message = 'Request submitted successful'
        else:
            res = 'error'
            message = ('Error occurred while processing the request,please check your inputs '
                       'and try gain')

        notification = res + '&message=' + message
        url = "?response=".join(
            [reverse(f'emkopo_product:{request.POST.get("next_url_name")}'), notification])
    return redirect(url)


def update_fsp(request):
    if request.method == 'POST':
        try:
            Fsp.objects.filter(pk=request.POST.get("id")).update(
                name=request.POST.get("name"),
                code=request.POST.get("code"),
                sysName=request.POST.get("sysName"),
                FSPBankAccount=request.POST.get("FSPBankAccount"),
                FSPBankAccountName=request.POST.get("FSPBankAccountName"),
                SWIFTCode=request.POST.get("SWIFTCode"),
                MNOChannels=request.POST.get("MNOChannels"),
            ),

            res = 'success'
            message = 'Request Approved successful'
        except Exception as e:
            res = 'error'
            message = ('Error occurred while processing the request,please check your inputs '
                       'and try again')

    notification = res + '&message=' + message
    url = "?response=".join(
        [reverse(f'emkopo_product:{request.POST.get("next_url_name")}'), notification])

    return redirect(url)


def delete_fsp(request):
    if request.method == 'POST':
        try:
            Fsp.objects.filter(pk=request.POST.get("id")).update(status=0)

            res = 'success'
            message = 'Request Approved successful'
        except Exception as e:
            res = 'error'
            message = ('Error occurred while processing the request,please check your inputs '
                       'and try again')

    notification = res + '&message=' + message
    url = "?response=".join(
        [reverse(f'emkopo_product:{request.POST.get("next_url_name")}'), notification])

    return redirect(url)

emkopo_product/views/product_catalog_view.py
import base64

from django.conf import settings
from django.views.generic.base import TemplateView
from django.shortcuts import redirect
from django.urls import reverse
from rest_framework.response import Response
from rest_framework import status
from xml.etree.ElementTree import Element, SubElement, tostring
import uuid

from emkopo_api.mixins import log_and_make_api_call
from emkopo_auth.mixins import LoginMixin
from emkopo_constants.constants import OUTGOING
from emkopo_mixins.date_mixins import convert_date_format
from emkopo_mixins.signature import load_private_key, sign_data
from emkopo_product.models import ProductCatalog, Currency, TermsCondition, Fsp


class ProductCatalogView(LoginMixin, TemplateView):
    template_name = f"emkopo_product/bootstrap/product-catalog.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        products = ProductCatalog.objects.filter(status=1)
        context.update(
            products=products
        )
        return context


def add_product(request, url=None):
    if request.method == 'POST':
        created = ProductCatalog.objects.create(
            ProductCode=request.POST['ProductCode'],
            ProductName=request.POST['ProductName'],
            ProductDescription=request.POST['ProductDescription'],
            ForExecutive=request.POST['ForExecutive'],
            MinimumTenure=request.POST['MinimumTenure'],
            MaximumTenure=request.POST['MaximumTenure'],
            InterestRate=request.POST['InterestRate'],
            ProcessFee=request.POST['ProcessFee'],
            Insurance=request.POST['Insurance'],
            MaxAmount=request.POST['MaxAmount'],
            MinAmount=request.POST['MinAmount'],
            RepaymentType=request.POST['RepaymentType'],
            Currency=request.POST['Currency']
        )

        if created:
            res = 'success'
            message = 'Request submitted successful'
        else:
            res = 'error'
            message = ('Error occurred while processing the request,please check your inputs '
                       'and try gain')

        notification = res + '&message=' + message
        url = "?response=".join(
            [reverse(f'emkopo_product:{request.POST.get("next_url_name")}'), notification])
    return redirect(url)


def add_currency(request, url=None):
    if request.method == 'POST':
        created = Currency.objects.get_or_create(
            name=request.POST['name'],
            code=request.POST['code'],
        )

        if created:
            res = 'success'
            message = 'Request submitted successful'
        else:
            res = 'error'
            message = ('Error occurred while processing the request,please check your inputs '
                       'and try gain')

        notification = res + '&message=' + message
        url = "?response=".join(
            [reverse(f'emkopo_product:{request.POST.get("next_url_name")}'), notification])
    return redirect(url)


def add_terms(request, url=None):
    if request.method == 'POST':
        created = TermsCondition.objects.update_or_create(
            ProductCatalog_id=request.POST['ProductCatalog'],
            TermsConditionNumber=request.POST['TermsConditionNumber'],
            Description=request.POST['Description'],
            TCEffectiveDate=convert_date_format(request.POST['TCEffectiveDate']),
        )

        if created:
            res = 'success'
            message = 'Request submitted successful'
        else:
            res = 'error'
            message = ('Error occurred while processing the request,please check your inputs '
                       'and try gain')

        notification = res + '&message=' + message
        url = "?response=".join(
            [reverse(f'emkopo_product:{request.POST.get("next_url_name")}'), notification])
    return redirect(url)


def update_product(request, res=None, message=None, url=None):
    if request.method == 'POST':
        try:
            product_id = request.POST.get("id")
            product = ProductCatalog.objects.get(pk=product_id)

            product.ProductCode = request.POST['ProductCode']
            product.ProductName = request.POST['ProductName']
            product.ProductDescription = request.POST['ProductDescription']
            product.ForExecutive = request.POST['ForExecutive']
            product.MinimumTenure = request.POST['MinimumTenure']
            product.MaximumTenure = request.POST['MaximumTenure']
            product.InterestRate = request.POST['InterestRate']
            product.ProcessFee = request.POST['ProcessFee']
            product.Insurance = request.POST['Insurance']
            product.MaxAmount = request.POST['MaxAmount']
            product.MinAmount = request.POST['MinAmount']
            product.RepaymentType = request.POST['RepaymentType']
            product.Currency = request.POST['Currency']

            product.save()

            res = 'success'
            message = 'Request Approved successful'
        except Exception as e:
            res = 'error'
            message = ('Error occurred while processing the request,please check your inputs '
                       'and try again')

    notification = res + '&message=' + message
    url = "?response=".join(
        [reverse(f'emkopo_product:{request.POST.get("next_url_name")}'), notification])

    return redirect(url)


def update_terms(request, res=None, message=None):
    if request.method == 'POST':
        try:
            terms = TermsCondition.objects.get(pk=request.POST.get("id"))
            terms.TermsConditionNumber = request.POST.get('TermsConditionNumber')
            terms.Description = request.POST.get('Description')
            terms.TCEffectiveDate = convert_date_format(request.POST.get('TCEffectiveDate'))

            terms.save()

            res = 'success'
            message = 'Request Approved successful'
        except Exception as e:
            res = 'error'
            message = ('Error occurred while processing the request,please check your inputs '
                       'and try again')

    notification = res + '&message=' + message
    url = "?response=".join(
        [reverse(f'emkopo_product:{request.POST.get("next_url_name")}'), notification])

    return redirect(url)


def delete_product(request, res=None, message=None):
    if request.method == 'POST':
        try:

            fsp = Fsp.objects.all().first()

            if not fsp:
                return Response({"error": "FSP not found"}, status=status.HTTP_404_NOT_FOUND)

            product = ProductCatalog.objects.get(pk=request.POST.get("id"))

            # Generate the XML data for API call
            xml_data = generate_xml_for_decommission(product, fsp)

            # Simulate the API call to the third-party system
            # response = send_to_third_party(xml_data)

            log_and_make_api_call(
                request_type=OUTGOING,
                payload=xml_data,
                signature="XYZ",  # Replace with actual signature if available
                url=settings.ESS_UTUMISHI_API
                # Replace with actual endpoint URL
            )

            ProductCatalog.objects.filter(pk=request.POST.get("id")).update(status=False)

            res = 'success'
            message = 'Request Approved successful'

        except ProductCatalog.DoesNotExist:
            res = 'error'
            message = 'Product not found.'
        except Exception as e:
            res = 'error'
            message = ('Error occurred while processing the request, please check your inputs '
                       'and try again')

    notification = res + '&message=' + message
    url = "?response=".join(
        [reverse(f'emkopo_product:{request.POST.get("next_url_name")}'), notification])

    return redirect(url)


def delete_terms(request, res=None, message=None):
    if request.method == 'POST':
        try:
            terms = TermsCondition.objects.get(pk=request.POST.get("id"))
            terms.status = False
            terms.save()
            res = 'success'
            message = 'Request Approved successful'
        except Exception as e:
            res = 'error'
            message = ('Error occurred while processing the request,please check your inputs '
                       'and try again')

    notification = res + '&message=' + message
    url = "?response=".join(
        [reverse(f'emkopo_product:{request.POST.get("next_url_name")}'), notification])

    return redirect(url)


def generate_xml_for_decommission(product, fsp):
    """
    Generate XML data for product decommission message.
    """
    # Create the root element
    document = Element("Document")
    data_elem = SubElement(document, "Data")

    # Create the header element
    header = SubElement(data_elem, "Header")
    SubElement(header, "Sender").text = fsp.name  # Get Sender from Fsp model
    SubElement(header, "Receiver").text = "ESS_UTUMISHI"
    SubElement(header, "FSPCode").text = fsp.code  # Get FSPCode from Fsp model
    SubElement(header, "MsgId").text = str(uuid.uuid4())  # Generate unique MsgId
    SubElement(header, "MessageType").text = "PRODUCT_DECOMMISSION"

    # Add the product code to the MessageDetails element
    message_details = SubElement(data_elem, "MessageDetails")
    SubElement(message_details, "ProductCode").text = product.ProductCode

    # Convert the XML Element to string (we'll sign this string)
    xml_string = tostring(document, encoding="utf-8").decode("utf-8")

    # Load the private key to sign the data
    private_key = load_private_key(settings.EMKOPO_PRIVATE_KEY)

    # Convert the XML string to bytes

emkopo_product/templates/emkopo_product/bootstrap/button/add-currency.html
<a href="javascript:;" data-tw-toggle="modal" data-tw-target="#add-currency" class="btn btn-primary mr-1 mb-1">Add Currency</a>
<div id="add-currency" class="modal" tabindex="-1" aria-hidden="true" data-tw-backdrop="static">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="intro-y box mt-5">
                <div class="flex flex-col sm:flex-row items-center p-5 border-b border-slate-200/60 dark:border-darkmode-400">
                    <h2 class="font-medium text-base mr-auto">
                        ADD CURRENCY
                    </h2>
                </div>
                <div id="input-groups" class="p-5">
                    <div class="preview">
                        <form action="{% url 'emkopo_product:add-currency' %}" method="post">
                            {% csrf_token %}
                            <div>
                                <div class="col-span-12 sm:col-span-12">
                                    <label for="fsp-name" class="form-label">Currency Name</label>
                                    <input id="fsp-name" name="name" type="text" class="form-control" placeholder="Currency Name">
                                </div><br>
                                <div class="col-span-12 sm:col-span-12">
                                    <label for="fsp-name" class="form-label">Currency Code</label>
                                    <input id="fsp-name" name="code" type="text" class="form-control" placeholder="Currency Code">
                                </div>
                            </div><br>
                            <div>
                                <input type="hidden" name="next_url_name" value="product-catalog">
                                <input type="submit" value="Submit" class="btn btn-primary w-1/2 sm:w-auto mr-2 pull-right">
                                <button type="button" data-tw-dismiss="modal" class="btn btn-outline-warning w-1/2 sm:w-auto mr-2">Cancel</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

emkopo_product/templates/emkopo_product/bootstrap/button/add-fsp.html
<a href="javascript:;" data-tw-toggle="modal" data-tw-target="#add-fsp" class="btn btn-success mr-1 mb-1">Add Financial Service Provider</a>
<div id="add-fsp" class="modal" tabindex="-1" aria-hidden="true" data-tw-backdrop="static">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="intro-y box mt-5">
                <div class="flex flex-col sm:flex-row items-center p-5 border-b border-slate-200/60 dark:border-darkmode-400">
                    <h2 class="font-medium text-base mr-auto">
                        ADD Financial Service Provider
                    </h2>
                </div>
                <div id="input-groups" class="p-5">
                    <div class="preview">
                        <form action="{% url 'emkopo_product:add-fsp' %}" method="post">
                            {% csrf_token %}
                            <div>
                                <div class="col-span-12 sm:col-span-12">
                                    <label for="fsp-name" class="form-label">FSP Name</label>
                                    <input id="fsp-name" name="name" type="text" class="form-control" placeholder="FSP Name">
                                </div><br>
                                <div class="col-span-12 sm:col-span-12">
                                    <label for="fsp-name" class="form-label">FSP Code</label>
                                    <input id="fsp-name" name="code" type="text" class="form-control" placeholder="FSP Code">
                                </div><br>
                                <div class="col-span-12 sm:col-span-12">
                                    <label for="fsp-name" class="form-label">FSP System</label>
                                    <input id="fsp-name" name="sysName" type="text" class="form-control" placeholder="FSP Code">
                                </div><br>
                                <div class="col-span-12 sm:col-span-12">
                                    <label for="fsp-name" class="form-label">FSP Bank Account</label>
                                    <input id="fsp-name" name="FSPBankAccount" type="text" class="form-control" placeholder="FSP Bank Account">
                                </div><br>
                                <div class="col-span-12 sm:col-span-12">
                                    <label for="fsp-name" class="form-label">FSP Bank Account Name</label>
                                    <input id="fsp-name" name="FSPBankAccountName" type="text" class="form-control" placeholder="FSP Bank Account Name">
                                </div><br>
                                <div class="col-span-12 sm:col-span-12">
                                    <label for="fsp-name" class="form-label">SWIFT Code</label>
                                    <input id="fsp-name" name="SWIFTCode" type="text" class="form-control" placeholder="SWIFT Code">
                                </div><br>
                                <div class="col-span-12 sm:col-span-12">
                                    <label for="fsp-name" class="form-label">MNO Channels</label>
                                    <input id="fsp-name" name="MNOChannels" type="text" class="form-control" placeholder="MNO Channels">
                                </div><br>
                            </div><br>
                            <div>
                                <input type="hidden" name="next_url_name" value="fsp">
                                <input type="submit" value="Submit" class="btn btn-primary w-1/2 sm:w-auto mr-2 pull-right">
                                <button type="button" data-tw-dismiss="modal" class="btn btn-outline-warning w-1/2 sm:w-auto mr-2">Cancel</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

emkopo_product/templates/emkopo_product/bootstrap/button/add-product.html
<a href="javascript:;" data-tw-toggle="modal" data-tw-target="#add-product" class="btn btn-success mr-1 mb-1">Add Product</a>
<div id="add-product" class="modal" tabindex="-1" aria-hidden="true" data-tw-backdrop="static">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="intro-y box mt-5">
                <div class="flex flex-col sm:flex-row items-center p-5 border-b border-slate-200/60 dark:border-darkmode-400">
                    <h2 class="font-medium text-base mr-auto">
                        ADD PRODUCT
                    </h2>
                </div>
                <div id="input-groups" class="p-5">
                    <div class="preview">
                        <form action="{% url 'emkopo_product:add-product' %}" method="post">
                            {% csrf_token %}
                            <div>
                                <div class="col-span-12 sm:col-span-12">
                                    <label for="fsp-name" class="form-label">Product Code</label>
                                    <input id="fsp-name" name="ProductCode" type="text" class="form-control" placeholder="Product Code">
                                </div><br>
                                <div class="col-span-12 sm:col-span-12">
                                    <label for="fsp-name" class="form-label">Product Name</label>
                                    <input id="fsp-name" name="ProductName" type="text" class="form-control" placeholder="Product Name">
                                </div><br>
                                <div class="col-span-12 sm:col-span-12">
                                    <label for="fsp-name" class="form-label">Product Description</label>
                                    <input id="fsp-name" name="ProductDescription" type="text" class="form-control" placeholder="Product Description">
                                </div><br>
                                <div>
                                    <label>For Executive</label>
                                    <div class="form-check mt-2">
                                        <input id="radio-switch-1" class="form-check-input" type="radio" name="ForExecutive" value="1" required>
                                        <label class="form-check-label" for="radio-switch-1">Yes</label>
                                    </div>
                                    <div class="form-check mt-2">
                                        <input id="radio-switch-2" class="form-check-input" type="radio" name="ForExecutive" value="0" required>
                                        <label class="form-check-label" for="radio-switch-2">No</label>
                                    </div>
                                </div><br>
                                <div class="col-span-12 sm:col-span-12">
                                    <label for="fsp-name" class="form-label">Minimum repayment period</label>
                                    <input id="fsp-name" name="MinimumTenure" type="text" class="form-control" placeholder="Minimum repayment period">
                                </div><br>
                                <div class="col-span-12 sm:col-span-12">
                                    <label for="fsp-name" class="form-label">Maximum repayment period</label>
                                    <input id="fsp-name" name="MaximumTenure" type="text" class="form-control" placeholder="Maximum repayment period">
                                </div><br>
                                <div class="col-span-12 sm:col-span-12">
                                    <label for="fsp-name" class="form-label">Percentage charged on loan amount</label>
                                    <input id="fsp-name" name="InterestRate" type="text" class="form-control" placeholder="Percentage charged on loan amount">
                                </div><br>
                                <div class="col-span-12 sm:col-span-12">
                                    <label for="fsp-name" class="form-label">Cost of loan processing percentage</label>
                                    <input id="fsp-name" name="ProcessFee" type="text" class="form-control" placeholder="Cost of loan processing percentage">
                                </div><br>
                                <div class="col-span-12 sm:col-span-12">
                                    <label for="fsp-name" class="form-label">Loan cover percentage</label>
                                    <input id="fsp-name" name="Insurance" type="text" class="form-control" placeholder="Loan cover percentage">
                                </div><br>
                                <div class="col-span-12 sm:col-span-12">
                                    <label for="fsp-name" class="form-label">Maximum Amount</label>
                                    <input id="fsp-name" name="MaxAmount" type="text" class="form-control" placeholder="Maximum Amount">
                                </div><br>
                                <div class="col-span-12 sm:col-span-12">
                                    <label for="fsp-name" class="form-label">Minimum Amount</label>
                                    <input id="fsp-name" name="MinAmount" type="text" class="form-control" placeholder="Minimum Amount">
                                </div><br>
                                <div class="col-span-12 sm:col-span-12">
                                    <label for="fsp-name" class="form-label">Frequency of loan repayment</label>
                                    <input id="fsp-name" name="RepaymentType" type="text" class="form-control" placeholder="Frequency of loan repayment">
                                </div><br>
                                <div>
                                    <label for="regular-form-1" class="form-label">Currency</label>
                                    <select name="Currency" class="form-select mt-2 sm:mr-2" aria-label="Currency">
                                        <option value="">Select Currency</option>
                                        {% for currency in currencies %}
                                            <option value="{{ currency.code }}">{{ currency.code }}</option>
                                        {% endfor %}
                                    </select>
                                </div><br>
                            </div><br>
                            <div>
                                <input type="hidden" name="next_url_name" value="product-catalog">
                                <input type="submit" value="Submit" class="btn btn-primary w-1/2 sm:w-auto mr-2 pull-right">
                                <button type="button" data-tw-dismiss="modal" class="btn btn-outline-warning w-1/2 sm:w-auto mr-2">Cancel</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>